version: 0.2

phases:
  pre_build:
    commands:
    - echo Installing npm dependencies
    - npm install
    - export NODE_ENV=production
    - npm run build
  build:
    commands:
    - echo Running unit tests for components
artifacts:
  files:
  - ./**/*
